global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'faculty-appraisal-monitor'

scrape_configs:
  - job_name: 'faculty-appraisal-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
    scrape_interval: 15s
